export const MOTIVATIONAL_QUOTES = [
  'Discipline is choosing between what you want now and what you want most.',
  'We are what we repeatedly do. Excellence, then, is not an act but a habit.',
  'The only bad workout is the one that didn\'t happen.',
  'Small daily improvements over time lead to stunning results.',
  'Motivation gets you started. Habit keeps you going.',
  'Don\'t count the days. Make the days count.',
  'Success is the sum of small efforts repeated day in and day out.',
  'The secret of your future is hidden in your daily routine.',
  'You don\'t rise to the level of your goals. You fall to the level of your systems.',
  'Consistency is the true foundation of trust.',
  'It\'s not about being perfect. It\'s about making progress.',
  'Win the morning, win the day.',
  'Suffer the pain of discipline or suffer the pain of regret.',
  'Hard choices, easy life. Easy choices, hard life.',
  'One day or day one. You decide.',
  'A year from now you\'ll wish you had started today.',
  'The man who moves a mountain begins by carrying away small stones.',
  'Strength does not come from physical capacity. It comes from an indomitable will.',
  'Champions don\'t create habits during the season. Habits create champions.',
  'Every action you take is a vote for the type of person you wish to become.',
  'The difference between who you are and who you want to be is what you do.',
  'Forge yourself daily. No shortcuts. No excuses.',
  'Discipline is the bridge between goals and accomplishment.',
  'You have to be willing to do the things today others won\'t, to have the things tomorrow others won\'t.',
  'Push yourself because no one else is going to do it for you.',
  'Great things never come from comfort zones.',
  'Dream it. Wish it. Do it.',
  'Success doesn\'t just find you. You have to go out and get it.',
  'The harder you work for something, the greater you\'ll feel when you achieve it.',
  'Don\'t stop when you\'re tired. Stop when you\'re done.',
  'Wake up with determination. Go to bed with satisfaction.',
  'Do something today that your future self will thank you for.',
  'Little by little, a little becomes a lot.',
  'It always seems impossible until it\'s done.',
  'Focus on progress, not perfection.',
  'You are one decision away from a completely different life.',
  'The body achieves what the mind believes.',
  'Make each day your masterpiece.',
  'Either you run the day, or the day runs you.',
];

export function getDailyQuote(): string {
  const day = new Date().getDate() + new Date().getMonth() * 31;
  return MOTIVATIONAL_QUOTES[day % MOTIVATIONAL_QUOTES.length];
}
